"""
Applet: Print Done
Summary: 3D print complete
Description: Displays a 3D print complete notification. Push from Home Assistant when a print finishes.
Author: tronbyt
"""

load("encoding/base64.star", "base64")
load("render.star", "render")
load("schema.star", "schema")

# Bambu Lab logo 24x24 PNG (same as bambu app)
BAMBU_LOGO_B64 = "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAJI0lEQVR4AQEYCef2AQCqVQMAVqv9AKtANwAIBMgA+v7/AAEAAQAAAAAAAAAAAAAAAAD/APwAEAYEAPD6VQAAAAAAEAarAPD6/AABAAQAAAAAAAAAAAAAAAAA/wD/AAYCAQD4/DgAVcDJAKpVAwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8B/wD///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8B/wAAAQcACAQCAAD//gAA//0AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD//wkA/gHWAPX62AALBQYACwUDAAEAAQD/APwAAP/+AAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/wAAA/8JACLu1QCm2jEA/Ps7APn9pwACAfoADwUEAAYDAgAA//4AAP/9AAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgH/AP4C7gDiD1AAXSjGAPsCHQDt/GIABwMZAPf7cAD9/9cACwUDAAsFAwAC/wEAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAD8AAMBAQAB/wUAAQH+AAkEMQAKA6gAEQPlAPn8fwD//bkAT70qAPr9OgD3/asAAwX8AAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAD//QD///4ABgMCAA0FCAD6/fsAAP/qAPv/BQD3/P4A9Pz4AAEBEgAKBW4AAwbXALFDxQD/ASAA9fNfAE87zgAAAAEAVqv9AgAAAAAAAAAAAAAAAAAA//4AAAD8AAEAAQALBQMADAUCAP3/1wD5+3AA4vEdAFO/vgAD/g8A/gACAAAABAD8//8A8vv8APj9/wAFAjoACwOmAAcL5QCswikAAAD/AP9/AgIAAAAAAAAAAAADAv8ABgMCAA4FBQABAfoA+f2nAPv7OwBPvSoA9/+4ACAQhQCsQUoAAQHvAAMBAAAAAAAAAQABAAEABAABAAEA+Pz9APH7+wAGAhEAAAAPAAAAAACr1gECAAAAAAAAAAAAAf8EAPv/2wD3/G8A+gMZAO38YgD9AB8AsUPFAAgD2AAPBmMAAAINAAEC/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAwAAAAQA+///AAMB/AAAAAAAAAAAAgBWq/0AAAAAABD+zgDLuygAAPy6AAf8fwARA+UACwamAAUCOgD7/vsA8vv8AAMA/AD+/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQD9/gEAAAAAAAAAAAIAf38CAAAAAQDtAhcAMkPDAAMG1wAKBW4AAQESAPH6/QD4/P0AAAABAAEEAP+/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEACvWAQAAAP4AAP8cAAsEOgDx+/4A+P3+AAAAAwABAQMAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAP4C+wD3/P0AAAACAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAB/gEAAAEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH9/2NufjV5wAAAAASUVORK5CYII="

BAMBU_GREEN = "#00AE42"
GREEN_BG = "#001A0A"

def main(config):
    task_name = config.get("task_name", "")
    if task_name.endswith(".3mf"):
        task_name = task_name[:-4]
    elif task_name.endswith(".gcode"):
        task_name = task_name[:-6]

    header = render.Column(children = [
        render.Box(height = 1, color = GREEN_BG),
        render.Box(
            height = 6, color = GREEN_BG,
            child = render.Row(
                expanded = True,
                main_align = "space_between",
                cross_align = "center",
                children = [
                    render.Padding(pad = (2, 0, 0, 0), child = render.Text("MR 3D", font = "tom-thumb", color = "#CCCCCC")),
                    render.Padding(pad = (0, 0, 2, 0), child = render.Text("DONE", font = "tom-thumb", color = BAMBU_GREEN)),
                ],
            ),
        ),
        render.Box(width = 64, height = 1, color = BAMBU_GREEN),
    ])

    children = [
        render.Text("COMPLETE", font = "tb-8", color = BAMBU_GREEN),
    ]
    if task_name:
        children.append(render.Box(height = 3))
        children.append(
            render.Marquee(
                width = 60,
                child = render.Text(task_name, font = "tom-thumb", color = "#AAAAAA"),
            ),
        )

    content = render.Box(
        height = 24, color = "#000000",
        child = render.Column(
            expanded = True,
            main_align = "center",
            cross_align = "center",
            children = children,
        ),
    )

    return render.Root(
        child = render.Column(children = [header, content]),
    )

def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Text(
                id = "task_name",
                name = "Task Name",
                desc = "Name of the completed print (passed via push config)",
                icon = "cube",
            ),
        ],
    )
